
export const PRIVILEGES = Object.freeze({
  SEE_CONTRACTS: 'CAN_SEE_CONTRACTS_PRIVILEGE',
  MODIFY_CONTRACTS: 'CAN_MODIFY_CONTRACTS_PRIVILEGE',
  SEE_PROJECTS: 'CAN_SEE_PROJECTS_PRIVILEGE',
  MODIFY_PROJECTS: 'CAN_MODIFY_PROJECTS_PRIVILEGE',
  SEE_USERS: 'CAN_SEE_USERS_PRIVILEGE',
  ACCESS_USERS: 'CAN_ACCESS_USERS_PRIVILEGE',
  MODIFY_USERS: 'CAN_MODIFY_USERS_PRIVILEGE',
  MODERATE_SERVICE_TICKETS: 'CAN_MODERATE_SERVICE_TICKETS_PRIVILEGE',
  MAKE_ENGINEER_RESPONSE: 'CAN_MAKE_ENGINEER_RESPONSE_PRIVILEGE',
  MODERATE_TICKET_RESPONSES: 'CAN_MODERATE_TICKET_RESPONSES_PRIVILEGE'
});